# Changed the base url to '/' from 'amphibiandisease.org' because it was throwing a 404
# when blog posts were clicked on while the site is on Netlify.
# Change when site is going live.

baseURL = "/"
languageCode = "en-us"
title = "Amphibian Disease Portal"
theme = "kube"
description = "Motivated by the decline of amphibians globally and the growing understanding of diseases as major factors, AmphibiaWeb and the US Forest Service are collaborating to develop a community-based, online repository and reporting site for data on major infectious diseases, especially chytridiomycosis. Our mission is to aggregate, visualize and share data from the community of active researchers archiving their completed and in progress datasets from laboratory experiments and field sites around the world. The amphibian fungal disease chytridiomycosis, caused by the fungal pathogen Batrachochytrium dendrobatidis (Bd) has caused the extinction of hundreds of amphibian species globally over the last few decades. In addition, a newly described fungal pathogen, B. salamandrivorans (Bsal), thought to have evolved in Asia and recently introduced to Europe, has caused mass die-offs in native European salamanders. Our ability to predict outbreaks caused by these pathogenic fungi is poor. To help understand and predict these phenomena we are creating a globally accessible site for aggregating information from tested samples (Bd and Bsal) including interactive visualization of these data and the on-going activities of participants. In this rapidly developing area of science, making information more quickly and readily available will enable the scientific community to test and build predictive models more efficiently. Making data readily available should facilitate both research and management/ conservation decisions.  We aim to be a repository for Bd and Bsal data from field and biocollection samples. Only by the community coming together to aggregate data will we be able to understand the disease dynamics of this major cause of amphibian declines worldwide."
Paginate = 4
# [Params]
#   author = "YOUR NAME HERE" # add your company name

[[menu.main]]
    name = "Projects"
    weight = -100
    url = "/projects/"
[[menu.main]]
    name = "Query"
    weight = -100
    url = "/query/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Contribute Data"
    weight = -100
    url = "/contributing/"
[[menu.main]]
    name = "Dashboard"
    weight = -100
    url = "/dashboard/"
